#!/usr/bin/env bash

npm run docs \
&& npm version minor \
&& git push --tags origin master \
&& apm publish -t $(cat package.json \
  | grep version \
  | head -1 \
  | awk -F: '{ print $2 }' \
  | sed 's/[",]//g')
