#!/usr/bin/env bash

TYPE=${1:-minor}

npm run docs \
&& npm version $TYPE \
&& git push --tags origin master \
&& VERSION=$(cat package.json \
  | grep version \
  | head -1 \
  | awk -F: '{ print $2 }' \
  | sed 's/[", ]//g') \
&& echo "Publishing version v$VERSION" \
&& apm publish --tag "v$VERSION"
